### ISSUE TITLE
SPIR-V 1.0 spec is out, and so is KhronosGroup/SPIRV-Tools

### ISSUE THREAD

**Issue by dneto0** [kristerw/spirv-tools#1]
Hi.  I'm glad to see your interest and work in SPIR-V.  (I didn't know about it until just now)
The SPIR-V 1.0 spec is now published.  See https://www.khronos.org/registry/spir-v/

The Khronos Group published some low level tools as well: See https://github.com/KhronosGroup/SPIRV-Tools
Clearly there's some overlap, as we both have an assembler and disassembler.  :-)
The syntax that the Khronos Group used is actually lower level than yours in some respects, with very little syntactic sugar.
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/syntax.md

The Khronos SPIR-V Tools handles these situations which would be useful for your tool to handle as well:
- it's nice to have special syntax for the enumerated values in the spec.  I think you probably do many of these, such as the extended instructions.
- syntactic sugar for mask expressions
- bounds checking for non-32bit types. e.g. if you specify a 12 bit integer, then do bounds checking on  the literals for that type.  Similar for floating point.
- watch out for parsing of OpSwitch.  The widths of the literals depends on the type of the value referenced by the selector.

Consider building on top of the binary parser in SPIRV-Tools.  It's meant to be built upon.  Or at least reuse its algorithms.  :-)

**Comment by kristerw** [comment]
Hi!

I'm planning to update to SPIR-V 1.0 in a few days.

I have not looked at the Khronos tools yet, but I will definitely try to use that code as much as possible. In particular, I expect that my assembler/disassembler will not make much sense now, so I'll probably remove them (they were originally just a temporary hack I needed when I started playing with the SPIR-V binaries. And that temporary hack then got out of hand… 😀)

**Comment by kristerw** [comment]
I updated to SPIR-V 1.0 a while back (although I have not yet decided what to do about the assembler/disassembler...)
